feed_fetcher:
  cron: "0 0 0 0 0"
  class: "FeedFetcherCronWorker"

stop_conflate:
  cron: "0 0 0 0 0"
  class: "StopConflateCronWorker"

feed_extend:
  cron: "0 0 0 0 0"
  class: "FeedExtendCronWorker"

feed_enqueue:
  cron: "0 0 0 0 0"
  class: "FeedEnqueueCronWorker"
